Peer contact
cyrilmuchemi/My_Portfolio pull request #4
Opened 2022-03-22 14:44 UTC by AbuRayhaan

##Portfolio: Added contact me page.

In this milestone, I did the following:
- Created a new branch.
- Updated the index.html file
- Updated the styles.css file.

2022-03-22 20:12 UTC, mikethreels requested changes
Hi Cyril, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-22 20:12 UTC, mikethreels commented on index.html
> +                         <textarea name="comments" maxlength="500"> Enter text here</textarea>
- [ ] please make sure the `<textarea>` also has the `required` attribute, right now a visitor can submit the form without leaving a message.

2022-03-23 08:16 UTC, prolajumokeoni approved these changes
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

_Check inline comments_


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-23 08:16 UTC, prolajumokeoni commented on index.html
> +                     </label>
### OPTIONAL
- [ ] Kindly add the "Enter text here"  as a placeholder so users don't need to clear this text before  adding their own text

2022-03-23 08:16 UTC, prolajumokeoni commented on index.html
> +                     </button>
## OPTIONAL

- [ ] Kindly add all button interactions so your design looks like the Figma design, check the screenshot below ⬇️ 
![button](https://user-images.githubusercontent.com/69638013/159653164-f15e339a-b33d-4cb1-a026-3306cf3af59d.png)

2022-03-23 08:23 UTC, cyrilmuchemi commented on index.html
> +                     </button>
I have submitted to the wrong activity. I have submitted to day 1 instead of day 3. How can I undo?

2022-03-23 08:40 UTC, prolajumokeoni commented on index.html
> +                     </button>
Hi @cyrilmuchemi, Kindly create a zendesk ticket to get this issue resolved

2022-03-23 08:55 UTC, AmaduKamara approved these changes
# Status: Approved 🟢🟢🟢 

Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-23 08:55 UTC, AmaduKamara commented on index.html
> +                     </label>
[ Optional Changes ] These optional changes won't stop your project from being approved but will improve your code and help make you become a better developer.

- [ ] Kindly remove the text you placed inside of the `textarea`. That text is supposed to be inside a placeholder attribute on the `textarea` tag like this `<textarea name="comments" maxlength="500" placeholder="Enter text here" required></textarea>`. Please fix that 👍

2022-03-23 08:55 UTC, AmaduKamara commented on styles.css
> +  background: #ff6b00;
[ Optional Changes ]

- [ ] Kindly add interaction to the button as requested by the previous reviewer.
Please check the Figma template for the hover, focus, and active styles on the button and them. Your design will look very nice and human-friendly.

2022-03-23 08:56 UTC, prolajumokeoni commented on index.html
> +                     </button>
> I have submitted to the wrong activity. I have submitted to day 1 instead of day 3. How can I undo?

Hi @cyrilmuchemi, what's the day 1 activity? to undo or get information how to get this resolved you have to create a Zendesk ticket, from my end the name of the activity tallies with the pull request submitted 👍🏿

2022-03-23 11:24 UTC, BenMukebo approved these changes
Hi @cyrilmuchemi , 👋 

# STATUS: Approved  🎉 
Your project is complete!  There is nothing else to say other than... it's time to merge it
Congratulations! 🎉  🎉 🎉 

![](https://media.giphy.com/media/vmtxnxveVUodG/giphy.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @BenMukebo ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-23 11:31 UTC, merged