Desktop Portfolio :red_circle:
cyrilmuchemi/My_Portfolio pull request #5
Opened 2022-03-24 11:58 UTC by cyrilmuchemi

- Adding CSS media queries
- Adding a desktop version to my portfolio

2022-03-24 23:59 UTC, OLIPLICHE requested changes
Hi @afikanzoro , 

Good job so far!
There are some issues that you still need to work on to get your project approved, you are almost there!

## Highlights
- Linter result is green ✔️
- Commit messages are meaningful✔️
- The pull request have a descriptive title telling you what changes are inside ✔️
- The pull request have a short summary describing introduced changes in more detail ✔️
- node_modules folder is in the .gitignore ✔️

## Required Changes ♻️

- [ ] Please make sure that after the Section's title, there are only 4 to 5 lines of text describing the student's experience. 

![7](https://user-images.githubusercontent.com/63972670/160027796-a2bfa45b-300f-474c-90ef-4bc63c529725.JPG)

- [ ] Kindly make sure there should be one input for Full name and this should take the space of both First Name and Last Name inputs (shown in the desktop version, Figma).
- This picture below is from your design
![9](https://user-images.githubusercontent.com/63972670/160028063-fa05b06a-6b6d-41b0-8424-907b191455a4.JPG)
- The below is from Figma design

![8](https://user-images.githubusercontent.com/63972670/160028185-4875f0f6-74e1-4f49-8c12-1a29fb20aea9.JPG)


- [ ] Please the featured project description text should take 4 to 5 lines.
- [ ] `See Project` button should take you to the GitHub repository




![3](https://user-images.githubusercontent.com/63972670/160028379-bde76a7f-c04b-490b-81d8-23f5488e1db0.JPG)



 

- [ ] **CHECK THE COMMENTS UNDER THE REVIEW**

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-24 23:59 UTC, OLIPLICHE commented on index.html
>            <div id="thirdTag">
- [ ] Please make sure when the project is hovered on with the mouse the description and dark opacity disappears and a "See Project" button appears to the bottom of the image and takes the whole image width.
- [ ] Kindly make sure the "See Project" button takes you to the GitHub repository.

![6](https://user-images.githubusercontent.com/63972670/160026496-5109ac5b-0052-4633-9762-a2a4addb74f2.JPG)

2022-03-24 23:59 UTC, OLIPLICHE commented on index.html
>          <p>A daily selection of privately personalized reads;
- [ ] Please the project description text should take 2 to 3 lines of text.
![5](https://user-images.githubusercontent.com/63972670/160026943-ada9b65d-e9c5-4c63-b40f-95f0cd23a18f.JPG)

2022-03-25 00:11 UTC, cyrilmuchemi commented on styles.css
> +@media screen and (max-width: 992px) {
@OLIPLICHE  On day 3 activity 4, we are told to ignore the figma design and implement only full name. Kindly confirm

2022-03-25 00:20 UTC, cyrilmuchemi commented on styles.css
> +@media screen and (max-width: 992px) {
@OLIPLICHE  haven't I used min-width 992px in my desktop version, which is higher that 768? Kindly explain why you find this to be off-point

2022-03-25 00:24 UTC, cyrilmuchemi commented on index.html
>            <div id="thirdTag">
@OLIPLICHE I don't understand the issue of disappearance as the hoover is working fine on my end. Can you kindly share a hint of the code you think I can use insead?

2022-03-25 00:26 UTC, OLIPLICHE commented on styles.css
> +@media screen and (max-width: 992px) {
Hi, you need to make sure that your desktop version looks like the one in the Figma design template that you chose([Project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/4_desktop_version.md#project-requirements))

2022-03-25 20:55 UTC, CollinsTatang approved these changes
Hi @cyrilmuchemi, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![image](https://user-images.githubusercontent.com/55596970/158098566-50966056-ce3d-4c4b-aac3-cce7a7d107fb.png)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-25 21:50 UTC, merged